# Generated by Django 4.2.16 on 2024-10-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='long_window',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='strategy',
            name='short_window',
            field=models.IntegerField(default=50),
        ),
    ]
